### ISSUE TITLE
Error when apply content

### ISSUE THREAD

**Issue by itreseau** [sivasamyk/graylog-contentpack-httpmonitor#1]
Hi!

When I applied the content of HTTP Monitor content pack, I've got an error :

Error!  × Could not apply bundle: org.graylog2.restclient.lib.APIException: API call failed POST http://@172.19.202.6:12900/system/bundles/55faa958e4b091eb4d2f2dec/apply returned 500 Internal Server Error body: {"type":"ApiError","message":"can't serialize class org.graylog2.plugin.streams.Stream$MatchingType"}

![http_mon_content_pack_error](https://cloud.githubusercontent.com/assets/14109928/9932445/288c1878-5d44-11e5-9389-ff77607d9af5.PNG)

**Comment by sivasamyk** [comment]
Can you let me know the graylog version you are using?

**Comment by itreseau** [comment]
Hi,

I’m using the latest version.
graylog-web-interface v1.2.0 (2136f0c) (Oracle Corporation 1.8.0_60 / Linux 3.19.0-28-generic)

**Comment by sivasamyk** [comment]
This is due to an issue while importing streams in graylog 1.2 source code. I have raised an issue in graylog [#1434](https://github.com/Graylog2/graylog2-server/issues/1434).

**Comment by itreseau** [comment]
OK thanks, I'm going to follow its resolution.

**Comment by itreseau** [comment]
The bug has been fixed. So how can I resolve my issue please. I don't know how i can modify file
containing : 
streamData.put(StreamImpl.FIELD_MATCHING_TYPE, streamDescription.getMatchingType());
to
streamData.put(StreamImpl.FIELD_MATCHING_TYPE, streamDescription.getMatchingType().name());

**Comment by sivasamyk** [comment]
If you have a development setup , you can pull latest code from [master](https://github.com/Graylog2/graylog2-server), build and test (I will do this verify this bug fix). Else you can wait for 1.2.1 release.

**Comment by itreseau** [comment]
Hmmm it's a pity :( I'm in production so i'm going to wait for the next release.

**Comment by sivasamyk** [comment]
I tested with latest graylog-server master branch code and content pack is working.

**Comment by itreseau** [comment]
OK thanks, i'm happy to know that the bug is really fixed :) I hope that the new release will be available soon...

**Comment by sivasamyk** [comment]
Here you go : Graylog 1.2.1 released with the fix https://www.graylog.org/graylog-1-2-1-is-now-available/

**Comment by itreseau** [comment]
I did the upgrade and it perfectly works,thank you very much :)
